# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 15:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.CharField(default=datetime.datetime(2016, 4, 2, 15, 47, 31, 693658, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=datetime.datetime(2016, 4, 2, 15, 48, 31, 583189, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(default=datetime.datetime(2016, 4, 2, 15, 48, 38, 510027, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
