# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160402_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.CharField(max_length=100),
        ),
    ]
