# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='J71',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k8991', models.CharField(max_length=1)),
            ],
        ),
    ]
