# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_j71'),
    ]

    operations = [
        migrations.DeleteModel(
            name='J71',
        ),
    ]
